In [2]:
import numpy as np
import pandas as pd

In [3]:
data=pd.read_csv('Thyroid_Diff.csv')
data

Age Gender Smoking Hx Smoking Hx Radiothreapy          Thyroid Function  \
0     27      F      No         No              No                 Euthyroid   
1     34      F      No        Yes              No                 Euthyroid   
2     30      F      No         No              No                 Euthyroid   
3     62      F      No         No              No                 Euthyroid   
4     62      F      No         No              No                 Euthyroid   
..   ...    ...     ...        ...             ...                       ...   
378   72      M     Yes        Yes             Yes                 Euthyroid   
379   81      M     Yes         No             Yes                 Euthyroid   
380   72      M     Yes        Yes              No                 Euthyroid   
381   61      M     Yes        Yes             Yes  Clinical Hyperthyroidism   
382   67      M     Yes         No              No                 Euthyroid   

            Physical Examination Adenopathy       Pathology     Focality  \
0     Single nodular goiter-left         No  Micropapillary    Uni-Focal   
1            Multinodular goiter         No  Micropapillary    Uni-Focal   
2    Single nodular goiter-right         No  Micropapillary    Uni-Focal   
3    Single nodular goiter-right         No  Micropapillary    Uni-Focal   
4            Multinodular goiter         No  Micropapillary  Multi-Focal   
..                           ...        ...             ...          ...   
378  Single nodular goiter-right      Right       Papillary    Uni-Focal   
379          Multinodular goiter  Extensive       Papillary  Multi-Focal   
380          Multinodular goiter  Bilateral       Papillary  Multi-Focal   
381          Multinodular goiter  Extensive    Hurthel cell  Multi-Focal   
382          Multinodular goiter  Bilateral       Papillary  Multi-Focal   

     Risk    T    N   M Stage                Response Recurred  
0     Low  T1a   N0  M0     I           Indeterminate       No  
1     Low  T1a   N0  M0     I               Excellent       No  
2     Low  T1a   N0  M0     I               Excellent       No  
3     Low  T1a   N0  M0     I               Excellent       No  
4     Low  T1a   N0  M0     I               Excellent       No  
..    ...  ...  ...  ..   ...                     ...      ...  
378  High  T4b  N1b  M1   IVB  Biochemical Incomplete      Yes  
379  High  T4b  N1b  M1   IVB   Structural Incomplete      Yes  
380  High  T4b  N1b  M1   IVB   Structural Incomplete      Yes  
381  High  T4b  N1b  M0   IVA   Structural Incomplete      Yes  
382  High  T4b  N1b  M0   IVA   Structural Incomplete      Yes  

[383 rows x 17 columns]

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 383 entries, 0 to 382
Data columns (total 17 columns):
 #   Column                Non-Null Count  Dtype 
---  ------                --------------  ----- 
 0   Age                   383 non-null    int64 
 1   Gender                383 non-null    object
 2   Smoking               383 non-null    object
 3   Hx Smoking            383 non-null    object
 4   Hx Radiothreapy       383 non-null    object
 5   Thyroid Function      383 non-null    object
 6   Physical Examination  383 non-null    object
 7   Adenopathy            383 non-null    object
 8   Pathology             383 non-null    object
 9   Focality              383 non-null    object
 10  Risk                  383 non-null    object
 11  T                     383 non-null    object
 12  N                     383 non-null    object
 13  M                     383 non-null    object
 14  Stage                 383 non-null    object
 15  Response              383 non-null    ob

In [5]:
data.isnull().sum()

Age                     0
Gender                  0
Smoking                 0
Hx Smoking              0
Hx Radiothreapy         0
Thyroid Function        0
Physical Examination    0
Adenopathy              0
Pathology               0
Focality                0
Risk                    0
T                       0
N                       0
M                       0
Stage                   0
Response                0
Recurred                0
dtype: int64

In [6]:
data.head()

Age Gender Smoking Hx Smoking Hx Radiothreapy Thyroid Function  \
0   27      F      No         No              No        Euthyroid   
1   34      F      No        Yes              No        Euthyroid   
2   30      F      No         No              No        Euthyroid   
3   62      F      No         No              No        Euthyroid   
4   62      F      No         No              No        Euthyroid   

          Physical Examination Adenopathy       Pathology     Focality Risk  \
0   Single nodular goiter-left         No  Micropapillary    Uni-Focal  Low   
1          Multinodular goiter         No  Micropapillary    Uni-Focal  Low   
2  Single nodular goiter-right         No  Micropapillary    Uni-Focal  Low   
3  Single nodular goiter-right         No  Micropapillary    Uni-Focal  Low   
4          Multinodular goiter         No  Micropapillary  Multi-Focal  Low   

     T   N   M Stage       Response Recurred  
0  T1a  N0  M0     I  Indeterminate       No  
1  T1a  N0  M0     I      Excellent       No  
2  T1a  N0  M0     I      Excellent       No  
3  T1a  N0  M0     I      Excellent       No  
4  T1a  N0  M0     I      Excellent       No

In [7]:
data.drop(['Hx Smoking','Hx Radiothreapy','Adenopathy','T','N','M','Response','Recurred'],axis=1,inplace=True)

In [8]:
data

Age Gender Smoking          Thyroid Function  \
0     27      F      No                 Euthyroid   
1     34      F      No                 Euthyroid   
2     30      F      No                 Euthyroid   
3     62      F      No                 Euthyroid   
4     62      F      No                 Euthyroid   
..   ...    ...     ...                       ...   
378   72      M     Yes                 Euthyroid   
379   81      M     Yes                 Euthyroid   
380   72      M     Yes                 Euthyroid   
381   61      M     Yes  Clinical Hyperthyroidism   
382   67      M     Yes                 Euthyroid   

            Physical Examination       Pathology     Focality  Risk Stage  
0     Single nodular goiter-left  Micropapillary    Uni-Focal   Low     I  
1            Multinodular goiter  Micropapillary    Uni-Focal   Low     I  
2    Single nodular goiter-right  Micropapillary    Uni-Focal   Low     I  
3    Single nodular goiter-right  Micropapillary    Uni-Focal   Low     I  
4            Multinodular goiter  Micropapillary  Multi-Focal   Low     I  
..                           ...             ...          ...   ...   ...  
378  Single nodular goiter-right       Papillary    Uni-Focal  High   IVB  
379          Multinodular goiter       Papillary  Multi-Focal  High   IVB  
380          Multinodular goiter       Papillary  Multi-Focal  High   IVB  
381          Multinodular goiter    Hurthel cell  Multi-Focal  High   IVA  
382          Multinodular goiter       Papillary  Multi-Focal  High   IVA  

[383 rows x 9 columns]

In [9]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 383 entries, 0 to 382
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype 
---  ------                --------------  ----- 
 0   Age                   383 non-null    int64 
 1   Gender                383 non-null    object
 2   Smoking               383 non-null    object
 3   Thyroid Function      383 non-null    object
 4   Physical Examination  383 non-null    object
 5   Pathology             383 non-null    object
 6   Focality              383 non-null    object
 7   Risk                  383 non-null    object
 8   Stage                 383 non-null    object
dtypes: int64(1), object(8)
memory usage: 27.1+ KB


In [10]:
from sklearn.preprocessing import LabelEncoder

In [11]:
le=LabelEncoder()

In [12]:
#y=data['Thyroid Function']
#x=data.drop(columns=['Thyroid Function'],axis=1)
#x

In [13]:
data['Gender']=le.fit_transform(data['Gender'])
data['Smoking']=le.fit_transform(data['Smoking'])
data['Physical Examination']=le.fit_transform(data['Physical Examination'])
data['Pathology']=le.fit_transform(data['Pathology'])
data['Focality']=le.fit_transform(data['Focality'])
data['Risk']=le.fit_transform(data['Risk'])
data['Stage']=le.fit_transform(data['Stage'])
data['Thyroid Function']=le.fit_transform(data['Thyroid Function'])


In [14]:
data

Age  Gender  Smoking  Thyroid Function  Physical Examination  Pathology  \
0     27       0        0                 2                     3          2   
1     34       0        0                 2                     1          2   
2     30       0        0                 2                     4          2   
3     62       0        0                 2                     4          2   
4     62       0        0                 2                     1          2   
..   ...     ...      ...               ...                   ...        ...   
378   72       1        1                 2                     4          3   
379   81       1        1                 2                     1          3   
380   72       1        1                 2                     1          3   
381   61       1        1                 0                     1          1   
382   67       1        1                 2                     1          3   

     Focality  Risk  Stage  
0           1     2      0  
1           1     2      0  
2           1     2      0  
3           1     2      0  
4           0     2      0  
..        ...   ...    ...  
378         1     0      4  
379         0     0      4  
380         0     0      4  
381         0     0      3  
382         0     0      3  

[383 rows x 9 columns]

In [15]:
data.isnull().sum()

Age                     0
Gender                  0
Smoking                 0
Thyroid Function        0
Physical Examination    0
Pathology               0
Focality                0
Risk                    0
Stage                   0
dtype: int64

In [16]:
y=data['Thyroid Function']
x=data.drop(columns=['Thyroid Function'],axis=1)
x

Age  Gender  Smoking  Physical Examination  Pathology  Focality  Risk  \
0     27       0        0                     3          2         1     2   
1     34       0        0                     1          2         1     2   
2     30       0        0                     4          2         1     2   
3     62       0        0                     4          2         1     2   
4     62       0        0                     1          2         0     2   
..   ...     ...      ...                   ...        ...       ...   ...   
378   72       1        1                     4          3         1     0   
379   81       1        1                     1          3         0     0   
380   72       1        1                     1          3         0     0   
381   61       1        1                     1          1         0     0   
382   67       1        1                     1          3         0     0   

     Stage  
0        0  
1        0  
2        0  
3        0  
4        0  
..     ...  
378      4  
379      4  
380      4  
381      3  
382      3  

[383 rows x 8 columns]

In [17]:
y

0      2
1      2
2      2
3      2
4      2
      ..
378    2
379    2
380    2
381    0
382    2
Name: Thyroid Function, Length: 383, dtype: int64

In [18]:
from sklearn.model_selection import train_test_split

In [19]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=0)

In [20]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()

In [21]:
x_train=sc.fit_transform(x_train)
x_test=sc.fit_transform(x_test)

In [22]:
x_train.shape

(268, 8)

# random forest

In [23]:
from sklearn.ensemble import RandomForestClassifier

In [24]:
rf=RandomForestClassifier(n_estimators=200,criterion='entropy',random_state=0)

In [25]:
rf.fit(x_train,y_train)

RandomForestClassifier(criterion='entropy', n_estimators=200, random_state=0)

In [26]:
pred1=rf.predict(x_test)

In [27]:
pred1

array([2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2,
       2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2])

In [28]:
#Evaluate the model
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [29]:
accuracy=accuracy_score(y_test,pred1)
conmat=confusion_matrix(y_test,pred1)

In [30]:
print(accuracy)

0.8608695652173913


In [31]:
conmat

array([[ 0,  0,  4,  0,  0],
       [ 0,  0,  2,  0,  0],
       [ 1,  4, 99,  0,  0],
       [ 0,  0,  2,  0,  0],
       [ 0,  0,  3,  0,  0]])

In [32]:
print(classification_report(y_test,pred1))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00         4
           1       0.00      0.00      0.00         2
           2       0.90      0.95      0.93       104
           3       0.00      0.00      0.00         2
           4       0.00      0.00      0.00         3

    accuracy                           0.86       115
   macro avg       0.18      0.19      0.19       115
weighted avg       0.81      0.86      0.84       115



C:\Users\sriman\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\sriman\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\sriman\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average,

# svm

In [33]:
from sklearn.svm import SVC 

In [34]:
svm= SVC(kernel="rbf")

In [35]:
svm.fit(x_train,y_train)

SVC()

In [36]:
pred2=svm.predict(x_test)

In [86]:
pred2

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2])

In [87]:
#Evaluate the model
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [88]:
accu=accuracy_score(y_test,pred2)
con=confusion_matrix(y_test,pred2)

In [89]:
print(accu)

0.9043478260869565


In [90]:
con

array([[  0,   0,   4,   0,   0],
       [  0,   0,   2,   0,   0],
       [  0,   0, 104,   0,   0],
       [  0,   0,   2,   0,   0],
       [  0,   0,   3,   0,   0]])

In [91]:
print(classification_report(y_test,pred2))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00         4
           1       0.00      0.00      0.00         2
           2       0.90      1.00      0.95       104
           3       0.00      0.00      0.00         2
           4       0.00      0.00      0.00         3

    accuracy                           0.90       115
   macro avg       0.18      0.20      0.19       115
weighted avg       0.82      0.90      0.86       115



C:\Users\sriman\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\sriman\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\sriman\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average,

# knn

In [43]:
from sklearn.neighbors import KNeighborsClassifier

In [44]:
knn=KNeighborsClassifier(n_neighbors=3)

In [45]:
knn.fit(x_train, y_train)

KNeighborsClassifier(n_neighbors=3)

In [46]:
#test the model
pred3=knn.predict(x_test)
pred3

array([0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 4, 2, 2, 2, 2, 2, 2,
       2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2])

In [47]:
#Evaluate the model
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [48]:
knn_accu=accuracy_score(y_test,pred3)
knn_con=confusion_matrix(y_test,pred3)

In [49]:
knn_accu

0.8695652173913043

In [50]:
knn_con

array([[ 1,  0,  3,  0,  0],
       [ 0,  0,  2,  0,  0],
       [ 2,  2, 99,  0,  1],
       [ 0,  0,  2,  0,  0],
       [ 0,  0,  3,  0,  0]])

In [51]:
print(classification_report(y_test,pred3))

              precision    recall  f1-score   support

           0       0.33      0.25      0.29         4
           1       0.00      0.00      0.00         2
           2       0.91      0.95      0.93       104
           3       0.00      0.00      0.00         2
           4       0.00      0.00      0.00         3

    accuracy                           0.87       115
   macro avg       0.25      0.24      0.24       115
weighted avg       0.83      0.87      0.85       115



C:\Users\sriman\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\sriman\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\sriman\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average,

# hybrid model-1

In [78]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import VotingClassifier
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [79]:
# Define base models
decision_tree = DecisionTreeClassifier(random_state=0)
svm = SVC(probability=True, random_state=0)
logistic_regression = LogisticRegression(random_state=0)

In [80]:
# Create a hybrid model with VotingClassifier
hybrid_model = VotingClassifier(
    estimators=[('dt', decision_tree), ('svm', svm), ('lr', logistic_regression)],
    voting='soft'  # Use soft voting to take probability into account
)

In [81]:
# Train the hybrid model
hybrid_model.fit(x_train, y_train)

VotingClassifier(estimators=[('dt', DecisionTreeClassifier(random_state=0)),
                             ('svm', SVC(probability=True, random_state=0)),
                             ('lr', LogisticRegression(random_state=0))],
                 voting='soft')

In [82]:
# Make predictions
y_pred = hybrid_model.predict(x_test)

In [83]:
# Evaluate the hybrid model
accuracy = accuracy_score(y_test, y_pred)
print(f"Hybrid Model Accuracy: {accuracy:.2f}")

Hybrid Model Accuracy: 0.90


In [84]:
hybrid1_con=confusion_matrix(y_test,y_pred)
hybrid1_con

array([[  1,   0,   3,   0,   0],
       [  0,   0,   2,   0,   0],
       [  2,   0, 102,   0,   0],
       [  0,   0,   2,   0,   0],
       [  0,   0,   3,   0,   0]])

In [85]:
hybrid1_cr=classification_report(y_test,y_pred)
hybrid1_cr

C:\Users\sriman\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\sriman\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\sriman\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average,

'              precision    recall  f1-score   support\n\n           0       0.33      0.25      0.29         4\n           1       0.00      0.00      0.00         2\n           2       0.91      0.98      0.94       104\n           3       0.00      0.00      0.00         2\n           4       0.00      0.00      0.00         3\n\n    accuracy                           0.90       115\n   macro avg       0.25      0.25      0.25       115\nweighted avg       0.84      0.90      0.86       115\n'

# hybrid model-2

In [58]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import StackingClassifier
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [59]:
# Define base models
base_models = [
    ('decision_tree', DecisionTreeClassifier(random_state=42)),
    ('knn', KNeighborsClassifier(n_neighbors=5)),
    ('svm', SVC(probability=True, random_state=42))
]

In [60]:
# Define the meta-model
meta_model = LogisticRegression()

In [61]:
# Create a stacked hybrid model
stacked_model = StackingClassifier(estimators=base_models, final_estimator=meta_model)

In [62]:
# Train the stacked model
stacked_model.fit(x_train, y_train)


C:\Users\sriman\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\model_selection\_split.py:776: UserWarning: The least populated class in y has only 3 members, which is less than n_splits=5.
  warnings.warn(
C:\Users\sriman\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\model_selection\_split.py:776: UserWarning: The least populated class in y has only 3 members, which is less than n_splits=5.
  warnings.warn(
C:\Users\sriman\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\model_selection\_split.py:776: UserWarning: The least populated class in y has only 3 members, which is less than n_splits=5.
  warnings.warn(


StackingClassifier(estimators=[('decision_tree',
                                DecisionTreeClassifier(random_state=42)),
                               ('knn', KNeighborsClassifier()),
                               ('svm', SVC(probability=True, random_state=42))],
                   final_estimator=LogisticRegression())

In [63]:
# Make predictions
y_pred = stacked_model.predict(x_test)

In [64]:
# Evaluate the stacked model
accuracy = accuracy_score(y_test, y_pred)
print(f"Stacked Model Accuracy: {accuracy:.2f}")

Stacked Model Accuracy: 0.90


In [66]:
hybrid2_con=confusion_matrix(y_test,y_pred)
hybrid2_con

array([[  0,   0,   4,   0,   0],
       [  0,   0,   2,   0,   0],
       [  0,   0, 104,   0,   0],
       [  0,   0,   2,   0,   0],
       [  0,   0,   3,   0,   0]])

In [77]:
hybrid2_cr=classification_report(y_test,y_pred)
hybrid2_cr

C:\Users\sriman\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\sriman\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\sriman\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average,

'              precision    recall  f1-score   support\n\n           0       0.33      0.25      0.29         4\n           1       0.00      0.00      0.00         2\n           2       0.91      0.98      0.94       104\n           3       0.00      0.00      0.00         2\n           4       0.00      0.00      0.00         3\n\n    accuracy                           0.90       115\n   macro avg       0.25      0.25      0.25       115\nweighted avg       0.84      0.90      0.86       115\n'

In [67]:
import joblib
joblib.dump(le,"thy_le")

['thy_le']

In [68]:
import joblib
joblib.dump(sc,"thy_sc")

['thy_sc']

In [69]:
import pickle
pickle.dump(svm,open('thy.pkl','wb'))